### ISSUE TITLE
Feature request: Integrate Find-GCP for automated marker detection

### ISSUE THREAD

**Issue by dsandson** [uav4geo/GCPEditorPro#10]
Automated computer vision detection of GCP markers is a fairly advanced feature set of typically proprietary software. User zsiki has produced what seems to be an effective open source alternative tailored to ODM.

It would be cool for many less advanced users to be able to package this up in GCPEditorPro since it is easy to install and manage. And a user interface would make it much easier to use.

Project;
[https://github.com/zsiki/Find-GCP](https://github.com/zsiki/Find-GCP)

Discussion on the community forums;
[https://community.opendronemap.org/t/automating-gcp-detection-on-images/7122](https://community.opendronemap.org/t/automating-gcp-detection-on-images/7122)

**Comment by pierotofy** [comment]
This is done! :clinking_glasses:
