### ISSUE TITLE
GCP Label problem

### ISSUE THREAD

**Issue by sbonaime** [uav4geo/GCPEditorPro#18]
With “2021/09/28_15:11:11.000" as a GCP Label, it is impossible to got to the GPC tagging window. When I click on the tag button, I return to the CVS import data

**Comment by coumbsek** [comment]
Reproduce easily after few tests. Seems to come from the fact that there are forward slash in the name.

Thus interpreation of page adresse for gcp does not works properly
`<a style="color: #fff;" class="btn btn-sm btn-primary mt-2" href="#/images-tagger/${item.name}">${imageIcon} Tag</a>`;`

**Comment by coumbsek** [comment]
Few more tests and research another suggestion is use encodeURIComponent for gcpName.
In `\src\app\gcps-map\gcps-map.component.ts` in becomes :
```
editImages(gcp: GCP) {
        this.ngZone.run(() => this.router.navigateByUrl('/images-tagger/' + encodeURIComponent(gcp.name))).then();
    }
```

I have replace it also in `\src\app\gcps-map\gcps-map.component.ts` but no idea if it is necessary.

I think this is the way to go.
Everything seems to work now.

Could someone double check this ?

**Comment by pierotofy** [comment]
I think it looks correct, thanks for looking into this. Could you open a pull request for this @coumbsek :pray: ?
