### ISSUE TITLE
Filter by distance problem

### ISSUE THREAD

**Issue by etorresmoya** [uav4geo/GCPEditorPro#26]
I have a gcp pro editor license, but when I use filter by distance, I dont receive the right images, is there any tutorial or manual for this function?
Thanks

**Comment by pierotofy** [comment]
Hi @etorresmoya 👋 are your images georeferenced? Typically the filter should give you the images that are closest (by radius) to the GCP that you are trying to tag.

**Comment by etorresmoya** [comment]
Thanks pierotofy, I will try with more distance. Best regards.
