### ISSUE TITLE
License still required after building.

### ISSUE THREAD

**Issue by being-someone-human** [uav4geo/GCPEditorPro#3]
I modified
https://github.com/uav4geo/GCPEditorPro/blob/master/src/app/storage.service.ts#L53
from 
            this.license = new DemoLicense();
to
            this.license = new DevLicense();
and had to remove
https://github.com/uav4geo/GCPEditorPro/blob/master/package.json#L29
to make the .bat file execute without errors.
But still after building it is still limiting me to run in demo mode or prompting me to supply a license.  This is true weather running from the win-unpacked executable or running the the installed version.

**Comment by pierotofy** [comment]
Mm, strange; what if you change DemoLicense https://github.com/uav4geo/GCPEditorPro/blob/c4621ad0a0d83f762d6823a3784cdfac29cb2b64/src/app/licenser.ts#L47 to and set `demo` to false and `dev` to true?

**Comment by being-someone-human** [comment]
I re-cloned from github and did as you suggested along with the previously mentioned changes and It's still prompting me to continue in demo mode or to activate.  

On a tangential note I had to run "npm run ng serve" as "ng serve" won't run unless you monkey with system paths.

**Comment by pierotofy** [comment]
I really don't know why it's not working :(  it seems to work OK when I modify the file as indicated in the README and run `dist.sh`. Perhaps it's the platform you're building on, I'm on Arch Linux. Check the output for possible errors. I would start from looking at the output of the `ng build` command and see if the built app (without electron) still asks for a license.

**Comment by pierotofy** [comment]
Ok so I finally had time to look into this; the `getLicense` method should be modified to always return a `DevLicense` (so don't just change `DemoLicense` to `DevLicense`, override the entire method to always return a `DevLicense`. I've updated the README to clarify this. :pray:
