### ISSUE TITLE
wrong epsg 28892

### ISSUE THREAD

**Issue by gisarts** [uav4geo/GCPEditorPro#7]
After I choose my csv file with EPSG 28992
![afbeelding](https://user-images.githubusercontent.com/4430776/95659023-bba4db80-0b1e-11eb-847a-10a4e0e2eb26.png)
and go to the next step I end up somewhere in Germany! Should be in the Netherlands.
![afbeelding](https://user-images.githubusercontent.com/4430776/95659008-b0ea4680-0b1e-11eb-8dce-26837f123614.png)
same with the proj string:
proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.999908 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +towgs84=565.2369,50.0087,465.658,-0.406857330322398,0.350732676542563,-1.8703473836068,4.0812 +no_defs +no_defs

**Comment by pierotofy** [comment]
If you swap the X/Y coordinates, do you end up in the right place?

**Comment by gisarts** [comment]
Hi Piero, 
Indeed, thanks for the tip.
gr Fons
